//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public int DefectId { get; set; }
        public int PartCode { get; set; }
        public int DefectStateCode { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
    }
}
