//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int RentId { get; set; }
        public int CarId { get; set; }
        public System.DateTime RentAt { get; set; }
        public Nullable<System.DateTime> ReturnAt { get; set; }
        public int LocationId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ReturnTime { get; set; }
        public System.DateTime BookAt { get; set; }
        public int Price { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
