//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocarEntities : DbContext
    {
        public SocarEntities()
            : base("name=SocarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarType> CarTypes { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<CodeCategory> CodeCategories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Defect> Defects { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Rent> Rents { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarInsurance> CarInsurances { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
    }
}
